collections:
  all_pages:
    output: true
    permalink: /:name/index.html
  subpages:
    output: true
    permalink: /:path
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
