collections:
  all_pages:
    output: true
    permalink: /:name/index.html
sass:
  sass_dir: _sass
  sourcemap: always
  style: compressed
site_language: de

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
