backend:
  name: github
  repo: manulari/rptest
  base_url: https://quirky-stonebraker-84d38f.netlify.app/
  auth_endpoint: /oauth/auth
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
