backend:
  name: github
  repo: manulari/rptest
  base_url: https://3ssli916pk.execute-api.eu-central-1.amazonaws.com
  auth_endpoint: /prod/auth
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'all_pages'
    label: 'All Pages'
    folder: '_all_pages'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'text' }
